name: Run security

on:
  push:
    branches:
      - master
  #schedule:
    #- cron: "30 20 * * Mon"
  workflow_dispatch:
jobs:
  integration-tests-security:
    runs-on: ubuntu-latest
    permissions:
       contents: write
       security-events: write
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.15.0
      with:
        target: 'https://www.saucedemo.com/'
        artifact_name: security_reports
        token: ${{ secrets.GITHUB_TOKEN }}
        allow_issue_writing: false
    - name: Restore security report
      if: always()
      uses: actions/download-artifact@v3
      with:
        name: security_reports
        path: automatizacion-boletia/security-reports